sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t md-frontend ./frontend
  - docker build -t md-nginx ./nginx
  - docker build -t md-api ./api
  - docker build -t md-worker ./worker

  # Login into Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images into the Docker Hub
  - docker push md-frontend md-nginx md-api md-worker